import Navbar from "@/components/Navbar";
import UserCredential from "@/context/UserCredential";
import "../styles/globals.css";

export const metadata = {
  title: "Firebase Auth",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserCredential>
        <body className="dark:bg-gray-900">
          <header>
            <Navbar />
          </header>
          {children}
        </body>
      </UserCredential>
    </html>
  );
}
